import type { Component } from '@nuxt/schema';
import * as path from 'node:path';

export { generateIconsIndex, generateIconsRegistry };

/**
 * Sort c
 *
 * @param {Component[]} components
 * @returns {Component[]}
 */
function sortComponents(components: Component[]): Component[] {
  return [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );
}

function generateIconsIndex(components: Component[]) {
  // const indexPath = path.join(componentsDir, 'index.ts');

  const sorted = sortComponents(components);

  const lines: string[] = [
    '// Auto-generated by nuxt-compose-icons. Do not edit.',
    '',
    ...sorted.map((c) => {
      // c.filePath is absolute; we want a relative "./Name"
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const declaration = `export { default as ${c.pascalName || base} } from './${base}';`;
      // declaration += `\n`;
      // declaration += `export const ${c.pascalName || base}: typeof import("${'./' + base + '.vue'}")['default']`;
      return declaration;
    }),
    '',
  ];

  return lines;

  // fs.writeFileSync(indexPath, lines.join('\n'), 'utf-8');
}

async function generateIconsRegistry(components: Component[]) {
  // const registryPath = path.join(componentsDir, 'icon-registry.ts');
  // console.log('📟 - registryPath → ', registryPath);

  const sorted = sortComponents(components);

  const registryPath = path.resolve('../runtime/utils/icon-registry.ts');

  const lines: string[] = [
    '// Auto-generated by nuxt-compose-icons. Do not edit.',
    '',
    'export interface IconRegistryEntry {',
    '  name: string;',
    '  pascalName: string;',
    '  kebabName: string;',
    '  importPath: string;',
    '}',
    '',
    'export const iconRegistryPath = ' + JSON.stringify(registryPath.replace(/\\/g, '\\\\')) + ';',
    // 'export const iconRegistryPath = ' + JSON.stringify(registryPath.replace(/\\/g, '\\\\')) + ';',
    '',
    'export const iconRegistry: IconRegistryEntry[] = [',
    ...sorted.map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const pascal = c.pascalName || base;
      const kebab = c.kebabName || base;
      return `  { name: '${pascal}', pascalName: '${pascal}', kebabName: '${kebab}', importPath: './${base}' },`;
    }),
    '];',
    '',
  ];

  return lines;

  // fs.writeFileSync(registryPath, lines.join('\n'), 'utf-8');

  // fs.writeFileSync(path.join('./runtime/utils/', 'icon-registry.ts'), lines.join('\n'), 'utf-8');
}

// /**
//  * Write a declaration file for the component to provide type completion in IDEs
//  *
//  * @param {string} declarationFilePath
//  * @param {string} componentName
//  * @returns {string} the declaration from given component name
//  */
// function generateDeclarationFile(components: Component[]): string {
//   console.log('📟 - declarationFilePath → ', declarationFilePath);
//   let declarationContent = '';
//   // if (!fs.existsSync(declarationFilePath)) {
//     // fs.mkdirSync(path.dirname(declarationFilePath), { recursive: true });
//     declarationContent = `// Auto-generated file for icon components completion
// declare module 'nuxt-compose-icons' {
//   export type IconComponents = {`;
//     // fs.readFileSync(declarationFilePath, 'utf-8');
//   }

//   // const exportStatements = fs
//   //   .readdirSync(componentDir)
//   //   .filter((file) => file.endsWith('.ts'))
//   //   .map((file) => `export * from './${file}';`)
//   //   .join('\n');

//   fs.writeFileSync(
//     declarationFilePath,
//     declarationContent +
//       `\n  ${componentName}: typeof import('./${componentName}').default;\n}\n` +
//       `export default ${componentName};\n`,
//     'utf-8',
//   );
//   return declarationFilePath;
// }
