import type { Component } from '@nuxt/schema';
import fs from 'node:fs';
import path from 'node:path';

export { writeIconRegistry as generateIconIndex, writeIconsIndex };

function writeIconsIndex(componentsDir: string, components: Component[]) {
  const indexPath = path.join(componentsDir, 'index.ts');

  const sorted = [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );

  const lines: string[] = [
    '// Auto-generated by nuxt-compose-icons. Do not edit.',
    '',
    ...sorted.map((c) => {
      // c.filePath is absolute; we want a relative "./Name"
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      return `export { default as ${c.pascalName || base} } from './${base}';`;
    }),
    '',
  ];

  fs.writeFileSync(indexPath, lines.join('\n'), 'utf-8');
}

function writeIconRegistry(componentsDir: string, components: Component[]) {
  const registryPath = path.join(componentsDir, 'icon-registry.ts');

  const sorted = [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );

  const lines: string[] = [
    '// Auto-generated by nuxt-compose-icons. Do not edit.',
    '',
    'export interface IconRegistryEntry {',
    '  name: string;',
    '  pascalName: string;',
    '  kebabName: string;',
    '  importPath: string;',
    '}',
    '',
    // 'export const iconRegistryPath = ' + JSON.stringify(registryPath.replace(/\\/g, '\\\\')) + ';',
    'export const iconRegistryPath = ' + JSON.stringify(registryPath.replace(/\\/g, '\\\\')) + ';',
    '',
    'export const iconRegistry: IconRegistryEntry[] = [',
    ...sorted.map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const pascal = c.pascalName || base;
      const kebab = c.kebabName || base;
      return `  { name: '${pascal}', pascalName: '${pascal}', kebabName: '${kebab}', importPath: './${base}' },`;
    }),
    '];',
    '',
  ];

  fs.writeFileSync(registryPath, lines.join('\n'), 'utf-8');
  fs.writeFileSync(
    path.resolve(__dirname, '../../runtime/utils/icon-registry.ts'),
    lines.join('\n'),
    'utf-8',
  );
}
