name: Buid and Deploy docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: 'pnpm'

      - name: Build with VitePress
        run: pnpm docs:build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          # TODO: add to Wiki https://github.com/github/vscode-github-actions/issues/222
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Set up SSH key
        run: |
          ls -la ~/.ssh

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy build with rsync
        run: rsync -avz ./docs.vitepress/dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/nuxt-icons.use-compose.com/
